import "@/app/globals.css";
import LayoutWithIntro from "@/layout/LayoutWithIntro";
import { NextIntlClientProvider } from "next-intl";
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import { routing } from "@/i18n/routing";
import Script from 'next/script';

// Reemplaza GTM-XXXXXXX con tu ID de GTM
const GTM_ID = 'GTM-NV5Q8CW';

export const metadata = {
  title: 'Geniorama',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {

  console.log('routing', routing)

  if (!routing.locales.includes(locale as any)) {
    console.log('no routing')
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        {/* Google Tag Manager */}
        <Script id="google-tag-manager" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','${GTM_ID}');
          `}
        </Script>
        {/* End Google Tag Manager */}
      </head>
      <body>
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe 
            src={`https://www.googletagmanager.com/ns.html?id=${GTM_ID}`}
            height="0" 
            width="0" 
            style={{ display: 'none', visibility: 'hidden' }}
          />
        </noscript>
        {/* End Google Tag Manager (noscript) */}
        <NextIntlClientProvider messages={messages}>
          <LayoutWithIntro>
            {children}
          </LayoutWithIntro>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
