import "@/app/globals.css";
import LayoutWithIntro from "@/layout/LayoutWithIntro";
import { NextIntlClientProvider } from "next-intl";
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import { routing } from "@/i18n/routing";

export const metadata = {
  title: 'Geniorama',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {

  console.log('routing', routing)

  if (!routing.locales.includes(locale as any)) {
    console.log('no routing')
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
          <NextIntlClientProvider messages={messages}>
            <LayoutWithIntro>
              {children}
            </LayoutWithIntro>
          </NextIntlClientProvider>
      </body>
    </html>
  )
}
